version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: clinica_fisio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    command: postgres -c shared_buffers=64MB
    volumes:
      - D:/Documentos/Proyectos/docker-data/data/pgdata:/var/lib/postgresql/18/docker

  backend:
    build: ./backend
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinica_fisio
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JAVA_OPTS: "-Xms128m -Xmx256m"
    command: >
      sh -c "./wait-for-it.sh db:5432 -- java -jar app.jar"
    volumes:
      - D:/Documentos/Proyectos/docker-data/data/backend:/app/data

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    volumes:
      - /app/node_modules
      - D:/Documentos/Proyectos/docker-data/data/frontend:/app/data