services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: clinica_fisio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: JDBC:postgresql://db:5432/clinica_fisio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"