--INSERT INTO ajustes_clinica (id, nombre, cif_nif, direccion, telefono, email, logo_url, serie_facturacion)
--VALUES (1, 'Clínica JotaJota', 'B12345678', 'Calle Fisioterapia 123', '954000000', 'info@jotajota.com', '/ajustes/imagenes/logo.png', 'F')
--ON CONFLICT (id) DO NOTHING;